### ISSUE TITLE
paper-loginscreen not yet on npm

### ISSUE THREAD

**Issue by eshikafe** [cforgeard/paper-loginscreen#2]
Any plans to publish this module on npm?

npm ERR! 404  '@polymer/paper-loginscreen' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

It will good to make this module fully compatible with Polymer 3.0.

**Comment by cforgeard** [comment]
OK, I will make a polymer 3.0 compatible of this component this weekend.

**Comment by cforgeard** [comment]
Done ! https://www.npmjs.com/package/paper-loginscreen
